version: '3'
services:
  backend:
    environment:
      DB_URL: "mongodb://mongo:27017/FS_Dev_Case"
    env_file:
      - .env.${NODE_ENV}
    ports:
      - "${DEBUG_PORT}:${DEBUG_PORT}" # Debug port