version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=${NODE_ENV}
    env_file: 
      - .env
      - .env.${NODE_ENV}
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/backend
      - /backend/node_modules
    depends_on:
      - mongo
    networks:
      - crypto-exchange-network

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - crypto-exchange-network

volumes:
  mongo-data:

networks:
  crypto-exchange-network:
    driver: bridge