version: '3'
services:
  backend:
    container_name: fs_backend
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: "${NODE_ENV}"
      DB_URL: "mongodb://mongo:27017/FS_Dev_Case"
    env_file:
      - .env.${NODE_ENV}
    ports:
      - "${PORT}:${PORT}" # App port
      - "${SOCKET_PORT}:${SOCKET_PORT}" # Socket port
      - "${DEBUG_PORT}:${DEBUG_PORT}" # Debug port
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    depends_on:
      - mongo
    networks:
      - fullstack-app-network

  mongo:
    container_name: fs_mongo
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - fullstack-app-network

volumes:
  mongo-data:


networks:
  fullstack-app-network:
    driver: bridge
